<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Prateeks-PC" name="Sanity Test" tests="17" failures="4" timestamp="24 Apr 2021 21:09:00 GMT" time="0.075" errors="0">
  <testcase name="Test1" time="0.005" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.005" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at TestRetryAnalyzer.RunTimeRetryTest.Test1(RunTimeRetryTest.java:13)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.005" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at TestRetryAnalyzer.RunTimeRetryTest.Test2(RunTimeRetryTest.java:19)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase name="Test3" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at TestRetryAnalyzer.RunTimeRetryTest.Test3(RunTimeRetryTest.java:25)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase name="Test4" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <skipped/>
  </testcase> <!-- Test4 -->
  <testcase name="Test4" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <skipped/>
  </testcase> <!-- Test4 -->
  <testcase name="Test4" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <skipped/>
  </testcase> <!-- Test4 -->
  <testcase name="Test4" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at TestRetryAnalyzer.RunTimeRetryTest.Test4(RunTimeRetryTest.java:31)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test4 -->
  <testcase name="Test5" time="0.0" classname="TestRetryAnalyzer.RunTimeRetryTest"/>
</testsuite> <!-- Sanity Test -->
